### ISSUE TITLE
Infobox icons

### ISSUE THREAD

**Issue by connorshea** [PCGamingWiki/overclocked#2]
The Infobox's icons (Wikipedia, SteamDB, WineDB, etc.) aren't the same size and therefore aren't aligned vertically. This is especially noticeable on mobile.

Example: 
<img width="76" alt="screen shot 2016-01-27 at 10 11 51 am" src="https://cloud.githubusercontent.com/assets/2977353/12621575/670b00ee-c4de-11e5-979e-b86504bfae99.png">

**Comment by soeb** [comment]
Resolved in a948c6d6.
